name: publish_helm_caller
run-name: Package and Publish Helm ${{ inputs.release_version_number }}
on:
  push
env:
#  GH_TOKEN: ${{ github.token }} # needed to gh cli commands
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  RELEASE_VERSION_NUMBER: "1.1.1"
  RELEASE_TAG_REF: "v1.1.1"

jobs:
  release_helm:
    name: Call publish helm
    # needs: [release_prepare, release_java, release_docker]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-helm.yml@issue/812-action-release-prepare-workflow
    with:
       release_version_number: 3.0.0
       release_tag_ref: v3.0.0
       root_helm_directory: "_infra/helm/secure-api-gateway-test-actions-server"
    secrets:
      FR_HELM_ACCESS_TOKEN: ${{ secrets.FR_HELM_ACCESS_TOKEN }}
      HELM_REPO: ${{ secrets.FR_HELM_REPO }}