name: manual_publish_helm_caller
run-name: Release Helm '${{ inputs.release_version_number }}' tag '${{ inputs.release_tag_ref }}'
on:
  workflow_dispatch:
    inputs:
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
      release_tag_ref:
        description: "Release tag ref created by release prepare (usually with pattern v${release_version_number}"
        required: true
        type: string

jobs:
  release_helm:
    name: Call publish helm
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-helm.yml@master
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
      root_helm_directory: "_infra/helm/secure-api-gateway-test-actions-server"
    secrets:
      FR_ARTIFACTORY_USER_ACCESS_TOKEN: ${{ secrets.FR_ARTIFACTORY_USER_ACCESS_TOKEN }}
      FR_HELM_REPO: ${{ secrets.FR_HELM_REPO }}