name: merge-master-manual
run-name: Master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Master integrity
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        name: set java and maven protected repository
        with:
          distribution: 'adopt'
          java-version: '14'
          architecture: x64
          cache: 'maven'
          server-id: forgerock-private-releases
          server-username: FR_ARTIFACTORY_USER # env variable for username in deploy
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable for token in deploy

      - name: Get version
        id: get_version
        run: |
          cat ~/.m2/settings.xml
          echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV
          echo "MAVEN_SERVER_COMMUNITY=maven.forgerock.org-community" >> $GITHUB_ENV
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

      - name: Context community repository
        if: contains( env.VERSION, 'SNAPSHOT')
        run: |
          ls -al
          cat ~/.m2/settings.xml
          echo "MAVEN_SERVER_COMMUNITY=maven.forgerock.org-community-snapshots" >> $GITHUB_ENV

      - name: Build maven
        run: |
          ls -al
          cat ~/.m2/settings.xml
          mvn clean install
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

      - uses: actions/setup-java@v3
        name: set java and maven comunity repository
        with:
          distribution: 'adopt'
          java-version: '14'
          architecture: x64
          cache: 'maven'
          server-id: ${{ env.MAVEN_SERVER_COMMUNITY }}
          server-username: FR_ARTIFACTORY_USER # env variable for username in deploy
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable for token in deploy

      - name: Release snapshot package to forgerock maven snapshot repository
        run: |
          ls -al
          cat ~/.m2/settings.xml 
          mvn -B deploy --file pom.xml
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
