name: publish_draft_and_pr_caller
run-name: Creates release Draft '${{ inputs.release_version_number }}' and PR
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
      release_tag_ref:
        description: "Release tag ref created by release prepare (usually with pattern v${release_version_number}"
        required: true
        type: string
      release_branch_ref:
        description: "Release branch created by release prepare (usually with pattern 'release/${release_version_number}"
        required: true
        type: string
env:
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:

  release_draft_and_pr:
    name: Call publish draft and PR
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-draft-and-pr.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_branch_ref: ${{ inputs.release_branch_ref }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}
      # reviewer: is optional default value set in the reusable workflow 'SecureApiGateway/release-reviewers'