name: caller_docker_workflow
run-name: Release Docker '${{ inputs.release_version_number }}' tag '${{ inputs.release_tag_ref }}'
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
      release_tag_ref:
        description: "Release tag ref created by release prepare (usually with pattern v${release_version_number}"
        required: true
        type: string
env:
#  GH_TOKEN: ${{ github.token }} # needed to gh cli commands
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:

  release_docker:
    name: Call publish docker
    # needs: [release_prepare]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-docker.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
      SERVICE_NAME: secure-api-gateway-test-actions-server
    secrets:
      GCR_CREDENTIALS_JSON: ${{ secrets.GCR_CREDENTIALS_JSON }}
      RELEASE_REPO: ${{ secrets.RELEASE_REPO }}