name: caller_release_workflow
run-name: Create release '${{ inputs.release_version_number }}'
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
env:
#  GH_TOKEN: ${{ github.token }} # needed to gh cli commands
  GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

jobs:

  release_prepare: # prepare for a release in scm, creates the tag and release branch with the proper release versions
    name: Call release prepare
    # uses: ./.github/workflows/release-prepare.yml # same repository
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-prepare.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
    secrets: # inherit only when is the same repository
      GPG_PRIVATE_KEY_BOT: ${{ secrets.GPG_PRIVATE_KEY_BOT }}
      GPG_KEY_PASSPHRASE_BOT: ${{ secrets.GPG_KEY_PASSPHRASE_BOT }}
      GIT_COMMIT_USERNAME_BOT: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
      GIT_COMMIT_AUTHOR_EMAIL_BOT: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

  release_java:
    name: Call publish java
    needs: release_prepare
    # uses: ./.github/workflows/release-prepare.yml # same repository
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-java.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
    secrets: # inherit only when is the same repository
      FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      FR_ARTIFACTORY_TOKEN: ${{ secrets.FR_ARTIFACTORY_TOKEN }}

  release_docker:
    name: Call publish docker
    needs: [release_prepare, release_java]
    # needs: [release_prepare]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-docker.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      SERVICE_NAME: test-actions-app
    secrets:
      GCR_KEY: ${{ secrets.GCR_KEY }}
      RELEASE_REPO: ${{ secrets.RELEASE_REPO }}

  release_helm:
    name: Call publish helm
    # needs: [release_prepare, release_java, release_docker]
    needs: [release_prepare, release_java]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-helm.yml@issue/812-action-release-prepare-workflow
    with:
       release_version_number: 5.0.0 ${{ inputs.release_version_number }}
       release_tag_ref: v5.0.0 ${{ needs.release_prepare.outputs.release_tag_ref }}
    secrets:
      FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      FR_ARTIFACTORY_TOKEN: ${{ secrets.FR_HELM_ACCESS_TOKEN }}
      HELM_REPO: ${{ secrets.FR_HELM_REPO }}

  release_draft_and_pr:
    name: Call publish draft and PR
    needs: [release_prepare, release_java, release_docker, release_helm]
    #needs: [release_prepare, release_java, release_helm]
    # uses: ./.github/workflows/release-prepare.yml # same repository
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-draft-and-pr.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_branch_ref: ${{ needs.release_prepare.outputs.release_branch_ref }}
      release_tag_ref: ${{ needs.release_prepare.outputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}
      reviewer: jorgesanchezperez