name: publish_java_caller
run-name: Release java '${{ inputs.release_version_number }}' tag '${{ inputs.release_tag_ref }}'
on:
  workflow_dispatch:
    inputs:
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
      release_tag_ref:
        description: "Release tag ref created by release prepare (usually with pattern v${release_version_number}"
        required: true
        type: string

jobs:

  release_java:
    name: Call publish java
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-java.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
    secrets:
      FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      FR_ARTIFACTORY_TOKEN: ${{ secrets.FR_ARTIFACTORY_TOKEN }}