name: publish_docker_caller
run-name: Release Docker '${{ inputs.release_version_number }}' tag '${{ inputs.release_tag_ref }}'
on:
  workflow_dispatch:
    inputs:
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string
      release_tag_ref:
        description: "Release tag ref created by release prepare (usually with pattern v${release_version_number}"
        required: true
        type: string

jobs:

  release_docker:
    name: Call publish docker
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-docker.yml@issue/812-action-release-prepare-workflow
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
      SERVICE_NAME: secure-api-gateway-test-actions-server
    secrets:
      GCR_CREDENTIALS_JSON: ${{ secrets.GCR_CREDENTIALS_JSON }}
      GCR_RELEASE_REPO: ${{ secrets.GCR_RELEASE_REPO }}