name: caller_release_no_maven_workflow
run-name: Create (no-maven) release '${{ inputs.release_version_number }}'
on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Release notes"
        required: false
        type: string
        default: ''
      release_version_number:
        description: "Provide release version number"
        required: true
        type: string

env:
  GH_TOKEN: ${{ github.token }} # needed to run gh cli commands

jobs:

  release_prepare_no_maven: # prepare for a release in scm, creates the tag and release branch with the proper release versions
    name: Call release prepare
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-prepare-no-maven.yml@issue/812-release-action-no-maven
    with:
      release_version_number: ${{ inputs.release_version_number }}
    secrets:
      GIT_COMMIT_USERNAME_BOT: ${{ secrets.GIT_COMMIT_USERNAME_BOT }}
      GIT_COMMIT_AUTHOR_EMAIL_BOT: ${{ secrets.GIT_COMMIT_AUTHOR_EMAIL_BOT }}

  release_docker:
    name: Call publish docker
    needs: [release_prepare_no_maven]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-docker.yml@issue/812-release-action-no-maven
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare_no_maven.outputs.release_tag_ref }}
      SERVICE_NAME: secure-api-gateway-test-actions-server
    secrets:
      GCR_CREDENTIALS_JSON: ${{ secrets.GCR_CREDENTIALS_JSON }}
      GCR_RELEASE_REPO: ${{ secrets.GCR_RELEASE_REPO }}

  release_helm:
    name: Call publish helm
    needs: [release_prepare_no_maven]
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-helm.yml@issue/812-release-action-no-maven
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ needs.release_prepare_no_maven.outputs.release_tag_ref }}
      root_helm_directory: "_infra/helm/secure-api-gateway-test-actions-server"
    secrets:
      FR_ARTIFACTORY_USER_ACCESS_TOKEN: ${{ secrets.FR_ARTIFACTORY_USER_ACCESS_TOKEN }}
      FR_HELM_REPO: ${{ secrets.FR_HELM_REPO }}

  release_draft:
    name: Call publish release draft
    uses: SecureApiGateway/secure-api-gateway-parent/.github/workflows/release-publish-draft-only.yml@issue/812-release-action-no-maven
    with:
      release_version_number: ${{ inputs.release_version_number }}
      release_tag_ref: ${{ inputs.release_tag_ref }}
      release_notes: ${{ inputs.notes }}


#  release_publish_draft:
#    name: Publish release draft
#    needs: [release_prepare_no_maven, release_docker, release_helm]
#    runs-on: ubuntu-latest
#    steps:
#      # https://github.com/actions/checkout
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      # Creates a release draft from tag
#      - name: Create github release draft
#        id: gh_release_draft
#        run: |
#          # Create a release from input tag
#          gh release create  --draft \
#          --verify-tag ${{ needs.release_prepare_no_maven.outputs.release_tag_ref }} \
#          --title "${{ inputs.release_version_number }}" --notes "${{ inputs.release_notes }}"
